CREATE TEMPORARY TABLE trip_data (
    data_type text,
    trip_creation_time text,
    route_schedule_uuid text,
    route_type text,
    trip_uuid text,
    source_center text,
    source_name text,
    destination_center text,
    destination_name text,
    od_start_time text,
    od_end_time text,
    start_scan_to_end_scan integer,
    is_cutoff boolean,
    cutoff_factor integer,
    cutoff_timestamp text,
    actual_distance_to_destination numeric,
    actual_time integer,
    osrm_time integer,
    osrm_distance numeric,
    factor numeric,
    segment_actual_time integer,
    segment_osrm_time integer,
    segment_osrm_distance numeric,
    segment_factor numeric
);
